### ISSUE TITLE
Should we add libuv source and document how to build this ?

### ISSUE THREAD

**Issue by gengjiawen** [cjihrig/uvwasi#17]
* Add libuv source to this repo ? And maybe change build system to CMake (build on windows)
* I am not familiar with make, Is it possible this can build on macOS

**Comment by cjihrig** [comment]
> and document how to build this (from the issue title)

It looks like @danbev has added this in https://github.com/cjihrig/uvwasi/pull/19. So once that lands, it will be documented.

> Add libuv source to this repo ?

I'm not sure that we need to vendor libuv at this point. I'd like to try just documenting that libuv is required (as well as a minimum required version). If it becomes an issue later we can always vendor it.

> I am not familiar with make, Is it possible this can build on macOS

Yes. If you can build Node.js on macOS, I'd imagine you already have the necessary tools on your machine.

> And maybe change build system to CMake (build on windows)

When I started this project, I threw together the minimum required Makefile to get development going. @danbev has since improved the Makefile. I'm definitely not opposed to moving to CMake, especially if it can make life easier for Windows users. CMake also has the benefit of being built on libuv. @danbev do you have any thoughts here since you've been working on the build?

**Comment by danbev** [comment]
> I'm definitely not opposed to moving to CMake, especially if it can make life easier for Windows users. CMake also has the benefit of being built on libuv.

I think these are good arguments for moving to CMake 👍

**Comment by cjihrig** [comment]
@gengjiawen is this something you'd like to work on?

**Comment by gengjiawen** [comment]
> @gengjiawen is this something you'd like to work on?

Yeap, I would like to work on build and doc, like `CMake`. But I maybe need help since I am not fluent in CMake.
